/**
 * Hand-written Typert remote contribution for better-webui.
 *
 * In a harness build this would normally be generated by the typert pipeline
 * (the package `/remote` + `/typert` artifacts). This file is the manual
 * equivalent, kept durable and reviewable while the plugin is developed
 * out-of-tree.
 */
import { z } from 'zod'
import type { InvocationDescriptor, TypertRemoteContribution } from '@deepseek-ai/dsh-typert-protocol'

const sessionIdSchema = z.string().min(1)
const metaResultSchema = z.object({
  trash: z.array(z.object({
    sessionId: z.string().min(1),
    trashedAt: z.number(),
  })),
  branches: z.array(z.object({
    sessionId: z.string().min(1),
    parentSessionId: z.string().min(1),
    branchAtSeq: z.number().int().nonnegative(),
  })),
})

function parameter(name: string, schema: z.ZodType): InvocationDescriptor['parameters'][number] {
  return {
    name,
    wire: name,
    source: 'json',
    codec: { mode: 'strict', typeSymbol: `@better-webui#${name}`, schema },
  }
}

function direct(
  method: string,
  parameters: readonly InvocationDescriptor['parameters'][number][],
  result: InvocationDescriptor['result'],
): InvocationDescriptor {
  return {
    id: `@better-webui/better-webui#${method}`,
    service: 'betterWebui',
    namespace: 'betterWebui',
    method,
    invocation: { kind: 'direct' },
    parameters: [...parameters],
    result,
  }
}

const voidResult: InvocationDescriptor['result'] = { mode: 'strict', typeSymbol: 'void', schema: z.void() }

/** Remote contribution consumed by the browser's `ctx.remote.$mount`. */
export const betterWebuiRemote: TypertRemoteContribution = {
  package: '@better-webui/better-webui',
  descriptors: [
    direct('trash', [parameter('sessionId', sessionIdSchema)], voidResult),
    direct('restore', [parameter('sessionId', sessionIdSchema)], voidResult),
    direct('destroy', [parameter('sessionId', sessionIdSchema)], voidResult),
    direct('branch', [
      parameter('sessionId', sessionIdSchema),
      parameter('atSeq', z.number().int().nonnegative()),
      parameter('childSessionId', z.string().min(1).optional()),
    ], { mode: 'strict', typeSymbol: '@better-webui#SessionId', schema: sessionIdSchema }),
    direct('meta', [], { mode: 'strict', typeSymbol: '@better-webui#Metadata', schema: metaResultSchema }),
  ],
}
